### ISSUE TITLE
`terraform-helm` chart should appear on helm.releases.hashicorp.com

### ISSUE THREAD

**Issue by aareet** [hashicorp/terraform-helm#30]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

helm.releases.hashicorp.com

### Helm Values

```yaml
# Copy-paste your Helm values.yaml here.
```

### Expected Behavior

The terraform-helm chart should appear

### Important Factoids

The chart appears correctly via command line, without requiring --devel
<img width="893" alt="Screen Shot 2021-04-22 at 8 08 56 AM" src="https://user-images.githubusercontent.com/33654/115738538-fe533600-a341-11eb-9b99-bafa98b85ac5.png">

### References

* #0000

**Comment by arybolovlev** [comment]
The registry PR has been merged. Closing this issue.
